package models

type W3uData struct {
	BaseUnitId   string
	CustomUnitId string
	Unam         string
	Umvs         string
	Umvr         string
	Umas         string
	Umis         string
	Umvt         string
	Util         string
	Uine         string
	Udro         string
	Uabi         string
	Umdl         string
	Usca         string
	Uspa         string
	Ua1c         string
	Ua1t         string
	Ua1b         string
	Ua1m         string
	Ua1z         string
	Utc1         string
	Ua1r         string
	Urb1         string
	Ua1s         string
	Ua1d         string
	Ucs1         string
	Ua1w         string
	Umh1         string
	Ua1g         string
	Udef         string
	Uarm         string
	Udty         string
	Uacq         string
	Ubui         string
	Upgr         string
	Ides         string
	Unsf         string
	Uhot         string
	Utip         string
	Utub         string
	Ubld         string
	Utyp         string
	Ufoo         string
	Ufor         string
	Ulbd         string
	Ulba         string
	Ulbs         string
	Ubba         string
	Ubsi         string
	Ubdi         string
	Ugol         string
	Ugor         string
	Ulum         string
	Ulur         string
	Umpm         string
	Umpr         string
	Uhpm         string
	Upri         string
	Upoi         string
	Urtm         string
	Usle         string
	Usin         string
	Usid         string
	Ulev         string
	Ucar         string
	Uhpr         string
	Uhrt         string
	Umpi         string
	Urac         string
	Usst         string
	Usrg         string
	Usma         string
	Utar         string
	Umvh         string
	Uico         string
	Usnd         string
	Uclb         string
	Utra         string
	Upap         string
	Ubs1         string
	Udp1         string
	Ubpy         string
	Utc2         string
	Ua1p         string
	Ubpx         string
}
